
-- AQUI O USUÁRIO FORNECE OS DADOS E A SENHA É CRIPTOGRAFADA COM A CHAVE MD5
INSERT INTO USUARIOS VALUES ('FALHADX9',HASHBYTES('MD5', '123456'));
--VER USUÁRIOS
SELECT * FROM USUARIOS
-- AQUI SE CRIA O LOGIN DO USUÁRIO
CREATE LOGIN FALHADX9
-- A SENHA DO USUÁRIO É ARMAZENADA CRIPTOGRAFADA
WITH PASSWORD = 'á Ü9IºY«¾VàWòˆ>'
-- AQUI É CRIADO O USUÁRIO PARA O LOGIN
CREATE USER FALHADX9 FOR LOGIN	ALHADX9

-- NESTE COMANDO CONCEDEMOS A FUNCAO DE VISUALIZAR PARA O USUÁRIO FALHADX9
GRANT SELECT TO FALHADX9
