--INSERIR DADOS NA TABELA USUARIOS

INSERT INTO USUARIOS VALUES ('Aphonso', 'Senha555');
INSERT INTO CLASSES VALUES ('Barbaro', 'Descricao do barbaro');
INSERT INTO HABILIDADES VALUES ('Lanca mortal'),('Escudo Supremo')
INSERT INTO PERSONAGENS VALUES ('DeuBug', 1,1);
INSERT INTO CLASSESHABILIDADES VALUES (1,1), (1,2);

INSERT INTO USUARIOS VALUES ('Danox', 'Senha777');
INSERT INTO CLASSES VALUES ('Monge', 'Descricao do monge');
INSERT INTO HABILIDADES VALUES ('Recuperar Vida');
INSERT INTO PERSONAGENS VALUES ('BitBug', 2,2);
INSERT INTO CLASSESHABILIDADES VALUES (2,2), (2,3);

SELECT * FROM USUARIOS;
SELECT * FROM CLASSES;
SELECT * FROM HABILIDADES;
SELECT * FROM PERSONAGENS;
SELECT * FROM CLASSESHABILIDADES;
