-- CRIA O BANCO DE DADOS
CREATE DATABASE RPGGAME;
--COLOCA EM USO O BANCO DE DADOS
USE RPGGAME;
--CRIA A TABELA DE USUÁRIOS
CREATE TABLE USUARIOS
(
   USERID INT PRIMARY KEY IDENTITY,
   EMAIL VARCHAR(150) UNIQUE NOT NULL,
   SENHA VARCHAR (255) NOT NULL
);
--CRIA A TABELA DE CLASSES
CREATE TABLE CLASSES(
   CLASSEID INT PRIMARY KEY IDENTITY,
   NOME VARCHAR(150) UNIQUE NOT NULL,
   DESCRICAO VARCHAR(255)
);
--CRIA A TABELA DE HABILIDADES
CREATE TABLE HABILIDADES(
HABILIDADEID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(150) UNIQUE NOT NULL
);
--CRIA A TABELA DE PERSONAGENS
CREATE TABLE PERSONAGENS(
PERSONAGEMID INT PRIMARY KEY IDENTITY,
NOMEPERSONAGEM VARCHAR(15) UNIQUE NOT NULL,
USUARIOID INT UNIQUE FOREIGN KEY REFERENCES USUARIOS(USERID),
CLASSEID INT FOREIGN KEY REFERENCES CLASSES(CLASSEID)
);
-- CRIA A TABELA QUE RELACIONA AS CLASSES COM AS HABILIDADES // NECESSÁRIO POIS, CASO CONTRÁRIO, TERIA UMA RELACAO N:N ENTRE AS CLASSES E HABILIDADES.
CREATE TABLE CLASSESHABILIDADES(
CLASSEID INT FOREIGN KEY REFERENCES CLASSES(CLASSEID),
HABILIDADEID INT FOREIGN KEY REFERENCES HABILIDADES(HABILIDADEID)
);